# -*- coding: utf-8 -*-
"""Ass .1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MN5ZXnKpL9_PtEZQENnyaYo_xCTyFtTk

# **Statistics Basics**

**Assignment QuestionsAssignment Questions**

1. Explain the different types of data (qualitative and quantitative) and provide examples of each. Discuss
nominal, ordinal, interval, and ratio scales.

- Qualitative (Categorical) Data: Describes qualities or characteristics.

  Nominal: Categories without order (e.g., gender, colors).

  Ordinal: Categories with order (e.g., ranks, satisfaction levels).

- Quantitative (Numerical) Data: Represents numbers.

  Interval: Numeric scale with no true zero (e.g., temperature in Celsius).

  Ratio: Numeric scale with true zero (e.g., weight, height).

2. What are the measures of central tendency, and when should you use each? Discuss the mean, median,
and mode with examples and situations where each is appropriate.

- Mean: Arithmetic average. Best when data is symmetric and no extreme outliers.

- Median: Middle value. Best when data is skewed or has outliers.

- Mode: Most frequent value. Best for categorical or repeated data.

Example:

    Test scores with extreme low values → Median.

    Shoe size popularity → Mode.

    Average salary in a balanced dataset → Mean.

3. Explain the concept of dispersion. How do variance and standard deviation measure the spread of data?

 - Dispersion = spread of data around the central tendency.

- Variance: Average of squared deviations from the mean.

- Standard Deviation (SD): Square root of variance, shows spread in same units as data.

- Higher SD → more variability.

4. What is a box plot, and what can it tell you about the distribution of data?

- Box Plot

  A graphical representation using the five-number summary (min, Q1, median, Q3, max).

  Shows spread, symmetry, skewness, and outliers.

  Helps quickly visualize data distribution.

5. Discuss the role of random sampling in making inferences about populations.

- Ensures every individual has equal chance of selection.

- Reduces bias and makes sample representative.

- Enables valid inferences about population.

6. Explain the concept of skewness and its types. How does skewness affect the interpretation of data?

- Measure of asymmetry in distribution.

- Positive Skew: Tail on right (e.g., income data). Mean > Median > Mode.

- Negative Skew: Tail on left (e.g., exam scores with many high marks). Mean < Median < Mode.

- Skewness affects which central tendency measure is most reliable.

7. What is the interquartile range (IQR), and how is it used to detect outliers?

- IQR = Q3-Q1
- Measures middle 50% spread.

- Used to detect outliers:

- Outlier if value < Q1 – 1.5×IQR or > Q3 + 1.5×IQR.

8. Discuss the conditions under which the binomial distribution is used.

- Fixed number of trials (n).

- Each trial has 2 outcomes (success/failure).

- Probability of success (p) is constant.

- Trials are independent.

   Example: Tossing a coin 10 times.

9. Explain the properties of the normal distribution and the empirical rule (68-95-99.7 rule).

- Bell-shaped, symmetric, mean = median = mode.

- Area under curve = 1.

- Empirical Rule:

    68% data within 1 SD of mean,

    95% within 2 SD,

    99.7% within 3 SD.

10. Provide a real-life example of a Poisson process and calculate the probability for a specific event.

 - Events occur independently at constant average rate.

- Example: Number of customer arrivals at a bank per hour.

11. Explain what a random variable is and differentiate between discrete and continuous random variables.

 - Variable whose values depend on outcomes of random process.

- Discrete: Countable (e.g., number of heads in 10 tosses).

- Continuous: Infinite within an interval (e.g., height, time).

12. Provide an example dataset, calculate both covariance and correlation, and interpret the results.

- X = [1, 2, 3, 4], Y = [2, 4, 6, 8]

  Covariance: Positive, since both increase together.

  Interpretation: Perfect positive linear relationship.
"""